### ISSUE TITLE
increase testing coverage

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/autoslider.core#16]

**Comment by shajoezhu** [comment]
- [ ] R/assert.R                       26      18  30.77%   2, 7, 18-27, 33-37, 43
- [ ] R/autoslideR_error.R              7       0  100.00%
- [ ] R/decorate.R                    138      50  63.77%   10, 49, 85-159, 186, 241-246, 296-309
- [ ] R/fastdocall.R                   28      13  53.57%   16, 20-21, 32-40, 45-46
- [ ] R/format_date.R                   9       9  0.00%    33-42
- [ ] R/ft_formats.R                   54      36  33.33%   54-59, 88-163
- [ ] R/func_wrapper.R                 36      20  44.44%   18-29, 36-44
- [ ] R/generate_output.R              57       4  92.98%   78-80, 82
- [ ] R/helper_functions.R             36      20  44.44%   16-20, 63-80
- [ ] R/log.R                          31       5  83.87%   35-39
- [ ] R/null_report.R                   4       0  100.00%
- [ ] R/package.R                       1       1  0.00%    72
- [ ] R/save_output.R                  58      12  79.31%   62-89, 140, 143-144
- [ ] R/spec.R                         60      15  75.00%   47-55, 98-99, 127, 131, 139-140, 142-143
- [ ] R/t_ae_pt_diff_slide.R          122      17  86.07%   34-45, 151, 183-189, 202
- [ ] R/t_ae_pt_slide.R                18       0  100.00%
- [ ] R/t_ae_pt_soc_diff_slide.R       17       0  100.00%
- [ ] R/t_ae_pt_soc_slide.R            17       0  100.00%
- [ ] R/t_ae_slide.R                   74       0  100.00%
- [ ] R/t_ae_summary_slide.R          154       0  100.00%
- [ ] R/t_aesi_slide.R                132       0  100.00%
- [ ] R/t_dd_slide.R                   23       0  100.00%
- [ ] R/t_dm_slide.R                   32       0  100.00%
- [ ] R/t_dor_slide.R                  65       0  100.00%
- [ ] R/to_ft_funs.R                  221     151  31.67%   15-233, 288-290, 318, 341-402, 420, 432, 440
- [ ] R/to_slides.R                   142      74  47.89%   55-65, 70, 93-98, 101-102, 104-107, 109-112, 129-145, 221-226, 251-319
- [ ] R/util.R                        300     174  42.00%   54, 69, 106-126, 185-278, 304-316, 359-368, 377-449, 462-465, 469, 475, 483-512, 529-535, 539, 568-571
- [ ] TOTAL                          1862     619  66.76%

**Comment by shajoezhu** [comment]
remaining todos

- [ ]  - requirement #0.15 'Format of xx.xx (xx.xx, xx.xx)' is not covered by any
- [ ]    test
- [ ]  - requirement #0.27 'Refactor active arm' is not covered by any test
- [ ]  - requirement #0.31 'Format of (xx%, xx%)' is not covered by any test
- [ ]  - requirement #0.36 'survival proportion afun' is not covered by any test
- [ ]  - requirement #0.40 'Generate flextable for preview first page' is not
- [ ]    covered by any test
- [ ]  - requirement #0.53 'Format of xx.xx (xx.x)' is not covered by any test
